FROM ruby:2.5-slim as stage1
LABEL maintainer "Christopher Snyder" <34378288+maliciousactor@users.noreply.github.com>

# environment config
ARG APT="-y --no-install-recommends --no-upgrade -o Dpkg::Options::=--force-confnew"
ENV RAILS_ENV development
ARG RAILS_ROOT=/app
ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"

# install dependencies
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install $APT build-essential gcc git libmariadbd-dev \
        libsqlite3-dev make nodejs patch zlib1g-dev yarn

# fetch and configure dradis
RUN git clone https://github.com/dradis/dradis-ce.git /app && \
    sed -i "s/ruby '2.4.1'/ruby '\>\= 2.4.1'/" /app/Gemfile && \
    sed -i 's@database:\s*db@database: /data@' /app/config/database.yml.template && \
    sed -i 's/config.force_ssl = true/config.force_ssl = false/' /app/config/environments/production.rb && \
    sed -i 's/:uglifier/Uglifier.new(harmony: true)/' /app/config/environments/production.rb

# ruby init
RUN gem update --system

# install dradis
RUN mkdir /data && \
    cd /app && ruby bin/setup && bundle exec rake assets:precompile && \
    sed -i '/gem/s/^# *//' /app/Gemfile.plugins && bundle install --path=vendor/bundle
RUN gem environment

# Stage 2
FROM ruby:2.5-slim

# environment config
ARG APT="-y --no-install-recommends --no-upgrade -o Dpkg::Options::=--force-confnew"
ENV RAILS_ENV development
ARG RAILS_ROOT=/app
ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"

COPY --from=stage1 /data /data
COPY --from=stage1 $RAILS_ROOT $RAILS_ROOT
# COPY --from=stage1 /usr/local /usr/local
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x entrypoint.sh && apt update && \
    DEBIAN_FRONTEND=noninteractive apt install $APT git libmariadb3 libsqlite3-0 zlib1g nodejs yarn && \
    DEBIAN_FRONTEND=noninteractive apt autoremove -y && \
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* && \
    rm -rf /data/development.sqlite3

RUN cd /app && gem install bundler:2.2.4 && bundle update rake
RUN cd /app && bundle exec rake assets:precompile

RUN cd /app && rm -rf app/assets vendor/assets node_modules

WORKDIR /app

VOLUME /app
VOLUME /data

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]
